### PR TITLE
Run image compress even if Rails.application.assets is nil

### PR DESCRIPTION
**Pull request by iggant**
Since rails/sprockets-rails@d7c7ee1#diff-b295f4f07d2e863f15e53eb2047cfd1f we can't rely on app.assets for register_preprocessor

When compile=false and we precompile assets
register_preprocessor?(app) method will always return false

### CODE REVIEW

**Comment by toy** [comment]
Thanks for contribution!
It would be much better if the differentiation of behaviour would be based on availability of methods instead of gem versions.
It seems that the check for presence of `app.assets` is not really needed as if options are set, but there are no assets, then the processor will not be used, so maybe it can be replaced with true without conditions.
Also #120 looks more concise; as calls to `register_preprocessor` are identical, it would be better to just find the object on which to call the method instead of duplicating code.

**Comment by iggant** [comment]
Rewrite conditions for register_preprocessor? 

For Sprocket intoduce new class ImageOptimProcessor, because proc object will use LegacyProcProcessor - this doesn't support return hash to configure asset 

by default Sprocket produce gzip file, if it has preprocessor for file, but this doesn't have sence because image is already optimized, 

if this pull request will be accepted https://github.com/rails/sprockets/pull/221 then sprocket will skip gzip file generation.

**Comment by iggant** [comment]
so we have: 
due to this https://github.com/rails/sprockets/pull/224 we agreed that if preprocessor retrun nil charset in result hash sprockets will not generate gzip file, and I rewrite image preprocessor

also rewrite code to fit your rubocop policies

**Comment by iggant** [comment]
This pull request https://github.com/rails/sprockets/pull/228 was merged to sprockets so can count on this behaiviour. 
do you have some rewrite request, probably change some code?

**Comment by toy** [comment]
Hey Anton, sorry for long wait with this.
I've finally looked into how to properly work with sprockets.
One thing I've noticed is that it would make more sense to register image_optim as a compressor (as described in [Extending Sprockets#Compressors](https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#compressors)), but unfortunately it doesn't work as compressors are finally used only for js and css (rails/sprockets#246).
Another thing is that a proc can still be used, but the number of arguments is important (https://github.com/rails/sprockets/blob/3.x/lib/sprockets/processing.rb#L234).
I'm trying to build a fix in [sprockets-rails-3 branch](/toy/image_optim/tree/sprockets-rails-3).

**Pull request closed without merging**
