### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by lukaselmer**

### CODE REVIEW

**Comment by toy** [comment]
Hi Lukas, thanks for contribution.

What do you think about adding `jonof/kenutils/pngout` to the main `brew install` command and maybe mentioning in pngout section that it should have already been installed.

And I've fixed the appveyor build, so please rebase on master.

**Comment by lukaselmer** [comment]
Good points, I agree. Done.

**Comment by toy** [comment]
Very good, but I've missed one more thing - it would be better if commit message would describe the change.

**Comment by lukaselmer** [comment]
Agree again 👍, done.

**Comment by toy** [comment]
Ausgezeichnet!

**Pull request merged**
