### PR TITLE
Add support for Oxipng

### PR DESCRIPTION
**Pull request by oblakeerickson**
Based on https://github.com/toy/image_optim/issues/167

Oxipng is a multi-threaded rust implementation of Optipng.

https://github.com/shssoichiro/oxipng

### CODE REVIEW

**Comment by coding-horror** [comment]
any movement on this? 🙏

**Comment by oblakeerickson** [comment]
@toy Thanks for the merge on #193 :) I was hoping it would fix the appveyor CI test, but it still failed. It doesn't appear to be from the missing oxipng binary any more though. It might just need to be re-ran?

I rebased this branch with master to get rid of the merge conflicts. Let me know if there is anything else I should update.

**Comment by toy** [comment]
@oblakeerickson I should've mention here the [worker-analysis branch](https://github.com/toy/image_optim/compare/worker-analysis) that I created to try to understand if optipng and oxipng should be both enabled by default, or if only one should be enabled depending on availability. One more reason is to try to understand if level `6` for optipng is needed (this default is there from the start). I also need to find time to try to make output of the `worker-analysis` more readable.
Any suggestions for a bunch of test images that I can throw at analysis script?

**Comment by oblakeerickson** [comment]
Ah okay, ya I didn't know you were working on that branch. 

For test images I used some from https://ftp.arl.army.mil/ftp/historic-computers/ just because I know they are large (several MB) and it was easiest to see a performance improvement with oxipng.

Specifically http://ftp.arl.army.mil/ftp/historic-computers/png/brlescI2.png 

One benchmark I ran initially when I made this PR on my 8 core computer:


```
✓ 5.529442969s oxipng --strip all -i0 -o 3 --quiet /tmp/3620b7d70423a01b5c0220210219-270942-4esp2o.png
3620b7d70423a01b5c02.png

Original Size: 6941148
New file size: 3790576
```

```
✓ 24.734980747s optipng -i0 -o 2 -quiet -- /tmp/0650117ed6b0e9b29f0d20210219-271187-1hj9m1p.png
0650117ed6b0e9b29f0d.png

Original Size: 6941148
New file size: 3790592
```

For the same [6.7mb image](http://ftp.arl.army.mil/ftp/historic-computers/png/brlescI2.png) oxipng compressed it in 5.5s compared to 24.7s with optipng.

**Comment by oblakeerickson** [comment]
Looks like switching to github actions is part of this work? I see you have been working on the [worker-analysis branch](https://github.com/toy/image_optim/compare/worker-analysis), so thank you ❤️

**Comment by toy** [comment]
Currently not easy to dedicate enough to opensource.
But yes, switching to github actions became a requirement. And sad as I was using travis for 8 years and the way their change happened was not beautiful, but github actions are at least much snappier even though not yet very polished.
While working on worker-analysis branch I've also found some possible problem with pngquant, as it seems to be not lossless in some cases even with options requiring it.

**Comment by toy** [comment]
Sorry for long wait, I was trying to understand if it makes a lot of sense to run both oxipng and optipng for same image, but for now I only can tell that for some images they both contribute to reducing size. Worker analysis script in current state was not very helpful to understand if running both is not mostly wasteful and I didn't find time to rework it, so just updated PR and I think it is better to merge and iterate later

**Comment by oblakeerickson** [comment]
@toy no worries on the wait, totally understand. Thank you for updating the PR :)

**Comment by oblakeerickson** [comment]
@toy Just following up and letting you know this is now live in discourse. Thanks again for helping out with this :)

https://github.com/discourse/discourse/commit/da9cd4f6928a36af77e98d0e44103d256d12bad5

**Pull request merged**
