### PR TITLE
Allow workers to timeout.

### PR DESCRIPTION
**Pull request by tgxworld**
https://github.com/toy/image_optim/issues/21

### CODE REVIEW

**Comment by tgxworld** [comment]
cc @SamSaffron

**Comment by tgxworld** [comment]
@toy Would you prefer to have the `timeout` option passed to `optimize_image` or `optimize_image!` instead? 

Also, I'm having trouble getting the tests to pass on JRuby as it might be related to 
https://github.com/jruby/jruby/issues/2684. Would love to have some help here.

**Comment by tgxworld** [comment]
Hmm I'm trying to think of another way to do this without `Timeout.timeout`. Will have a think about it.

**Comment by toy** [comment]
@tgxworld I was late to reply while it was open. Anyway nice and thanks for contribution.
I would prefer a global config exactly as you did. Maybe even better to allow it to be set also per worker somewhat like for `allow_lossy`, some tools tend to be more time hungry than others, so setting global timeout to for example 30 seconds and timeout for some specific worker to 300 seconds.
Don't forget to add an entry to changelog and add the option to cli options and readme.

**Pull request closed without merging**
