### PR TITLE
Added -strip option to optipng

### PR DESCRIPTION
**Pull request by jwidderich**
Support the auxiliary chunk stripping option of optipng. Disabled by default. You can either pass a list of png chunknames or :all.

### CODE REVIEW

**Comment by toy** [comment]
Thanks for contribution!

I was going to write only latter notes, but while checking if `all` saves transparency chunk, found that unfortunately there is a problem with `optipng` as it does not yet accept anything except `all` for strip option (it will abort with `** Error: Manipulation of individual chunks is not implemented`). So currently strip worker option should be a boolean.

It should be on by default as other workers (`jpegoptim`, `jpegtran`, `pngcrush` and `pngout`) by default remove all non essential data chunks.
Please use `script/update_worker_options_in_readme` instead of adding options by hand.
Better place for excluding `/.idea/` is in `.git/info/exclude` as it specific to your workflow, have a look at [official gitignore documentation](http://git-scm.com/docs/gitignore#_description).

**Comment by jwidderich** [comment]
hey @toy,
I updated the pull request according to your suggestions, sorry that I didn't check the individual chunk removal before sending the pull request.

**Comment by toy** [comment]
Looks good, could you please add a changelog entry, squash commits to a mininum amount you seem fit and force push the branch?

**Comment by toy** [comment]
Once more thanks for contribution! And don't worry, you are doing great!

**Comment by SamSaffron** [comment]
very dangerous option to be adding here as on by default, default optipng installed by ubuntu does not support it and crashes out (0.6.4) requires 0.7+ to actually work.

**Comment by toy** [comment]
@SamSaffron I've fixed this in #106, though the easy solution is to use `image_optim_pack` :)

**Comment by SamSaffron** [comment]
thanks heaps !

**Pull request merged**
