### PR TITLE
add libjpeg-dev to install instructions

### PR DESCRIPTION
**Pull request by acrogenesis**
I was missing libjpeg-dev on a fresh install of ubuntu 14.04

### CODE REVIEW

**Comment by toy** [comment]
Hey Adrian,

Thanks for contribution. Do you need it for building `jpeg-recompress`?
Could you please place it so it is ordered alphabetically as other package names?

**Comment by acrogenesis** [comment]
@toy 
I really don't remember which one asked me `libjpeg-dev` to build.. I've already placed it alphabetically ordered.

**Comment by toy** [comment]
@acrogenesis After running the original `apt-get` command on a fresh ubuntu 14.04 leaves me with `pngout` and `svgo` not installed, but both they don't need `libjpeg-dev`. Even `jpeg-recompress` doesn't depend on it.

**Comment by acrogenesis** [comment]
I started a new droplet on DigitalOcean after running `sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant` and trying to install `jpegoptim` it say's:
`Cannot find libjpeg or you have too old version (v6 or later required).`

Installing `libjpeg-dev` solves it.

screen shot 2015-12-10 at 4 43 08 pm

**Comment by toy** [comment]
But you are compiling jpegoptim, the `apt-get` command is for installing prebuilt binaries. So `libjpeg-progs` provides `jpegtran`, but `libjpeg-dev` is only needed to compile binaries.
Also I've noticed that lots of binaries provided through `apt-get` are outdated, so I suggest to use `image_optim_pack` as you are on linux.

**Comment by oblakeerickson** [comment]
Just doing a little housekeeping... I think we can close this PR? It's quite old and libjpeg-dev doesn't appear to be required.

Just for reference the [Discourse install guide ](https://raw.githubusercontent.com/discourse/discourse/master/docs/DEVELOPER-ADVANCED.md) which uses image_optim and installs many apt based packages does not need the libjpeg-dev package when installing jpegoptim.

**Comment by acrogenesis** [comment]
Thanks for this great project 👍

**Pull request closed without merging**
