### PR TITLE
FEATURE: Timeout option for ImageOptim.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
@toy Please review :) Thank you!

**Comment by tgxworld** [comment]
Not sure what is going on with appveyor here

screenshot from 2018-07-09 10-19-48

**Comment by toy** [comment]
I'm also not sure what is with appveyor, but can be ignored till merging.

As I understand you wanted to change worker timeout in #149 to image optimisation timeout as in this PR.

**Comment by tgxworld** [comment]
> As I understand you wanted to change worker timeout in #149 to image optimisation timeout as in this PR. I think it is better to already think about possibility of both options. Maybe image_timeout for whole image handling and timeout for worker timeout, do you think it will be clear?

I'm only looking to implement a global timeout for image optim.

> Do I understand right that you want timeout exception to lead to abort of cli?

Yup it should abort the CLI as well :)

**Pull request closed without merging**
